# Package Overview
package_name: insur_churn

# Data Files
training_data_file: Train.csv
test_data_file: Test.csv

pipeline_name: xgb_classification
pipeline_save_file: xgb_classification_output_v

# Variables
# The variable we are attempting to predict (sale price)
target: label

features:
  - feature_0
  - feature_1
  - feature_2
  - feature_3
  - feature_4
  - feature_5
  - feature_7
  - feature_14
  - feature_15


numerical_vars:
  - None


categorical_vars:
  - None

temporal_vars: None

# Validation
# numerical variables with NA in train set
numerical_vars_with_na:
  - None

numerical_na_not_allowed:
  - None

# set train/test split
test_size: 0.1

# to set the random seed
random_state: 0

# model hyper-parameters
colsample_bytree: 0.65
gamma: 0.35
learning_rate: 0.13
max_depth: 7
min_child_weight: 4.0
n_estimators: 350
subsample: 0.94
